# version of the docker compose
version: "3.9"
services:
  twit_backend:
    # path where is the Dockerfile
    build: ./backend
    ports:
      - "80:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      FLASK_ENV: development
  twit_frontend:
    build: ./frontend/twimetaking
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/twimetaking:/user/src/app
    depends_on:
      - twit_backend